# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'Piensa en TIC' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Piensa en TIC
  pod 'MFSideMenu'
  pod 'IQKeyboardManagerSwift','4.0.6'
  pod 'Alamofire', '~> 4.0'
  pod 'youtube-ios-player-helper', '~> 0.1.6' 
end
